### ISSUE TITLE
半自动可以抢，全自动不可以抢

### ISSUE THREAD

**Issue by cheng1992zhen** [hznge/LuckPicker#1]
全自动不可以抢，你在手机上可以抢吗？全自动是哪里出了问题呢？

**Comment by hznge** [comment]
我再测试下,我的手机是红米note 3 全网通高配.Android 6.0, MiUi 8.2, 请问下你的手机详情是哪个?

**Comment by cheng1992zhen** [comment]
我的是华为P6 U06 EMUI 3.0 。RedPacketService亲测可用。至于HongbaoService却抢不到，没有反应。HongbaoService是基于geeeeeeeeek-WeChatLuckyMoney修改的吗？

**Comment by hznge** [comment]
你可以再试一下,现在应该可以自动抢红包了

**Comment by cheng1992zhen** [comment]
你的微信是最新版的吗？我的微信是最新版的6.5.7，Android版本是4.4. 来红包了，全自动没有任何反应，都不会进入微信。

**Comment by hznge** [comment]
微信版本是最新的.我去确认一下你说的问题

**Comment by cheng1992zhen** [comment]
HongbaoService之前不是基于geeeeeeeeek-WeChatLuckyMoney修改的吗？现在你已经全部改了吗？

**Comment by hznge** [comment]
现在应该没什么问题了,还是改回基于geeeeeeeek的算法实现.

**Comment by cheng1992zhen** [comment]
谢谢你，我最近也在研究这个，这次是真的可以抢了。想请教下，geeeeeeeek源码中是哪里出了问题，导致不能抢红包了呢？你是改了哪里？我能加你微信或者QQ吗？

**Comment by hznge** [comment]
微信的receivedUI的包名,微信版本更新(6.5.7)后,LUCKY_MONEY_RECEIVED_UI为"com.tencent.mm.plugin.luckymoney.ui.En_fba4b94f"(也可能是因为我的手机上装的是Play版的原因).
我的qq就是邮箱:hznge@qq.com
